import { useEffect, useState } from 'react';
import { useStore } from '../store';
import { supabase } from '../lib/supabase';
import { reportRows } from '../lib/support';

export default function Archives() {
  const {data,refreshPatientData,storageError,loadingRecords}=useStore();
  const [category,setCategory]=useState('mothers'),[query,setQuery]=useState(''),[show,setShow]=useState('Archived'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[caregivers,setCaregivers]=useState([]),[loading,setLoading]=useState(false);
  const loadCaregivers=async()=>{setLoading(true);setError('');try{const rows=[];for(let offset=0;;offset+=500){const result=await supabase.from('caregiver_requests').select('*').order('id').range(offset,offset+499);if(result.error)throw result.error;rows.push(...result.data);if(result.data.length<500)break;}setCaregivers(rows);}catch(e){setError(e.message);}finally{setLoading(false);}};
  useEffect(()=>{if(category==='caregivers')loadCaregivers();},[category]);
  const source=category==='caregivers'?caregivers.map(c=>({...c,name:c.full_name,archived:Boolean(c.archived_at)})):data[category];
  const rows=source.filter(p=>(show==='Archived'?p.archived:!p.archived)&&`${p.name} ${p.recordCode||''} ${p.contact_number||''}`.toLowerCase().includes(query.toLowerCase()));
  const change=async p=>{setBusy(true);setError('');setNotice('');try{const result=category==='caregivers'?await supabase.rpc('set_caregiver_archived',{request_id:p.id,archive_record:!p.archived}):await supabase.from(category).update({status:p.archived?'active':'archived'}).eq('id',p.id);if(result.error)throw result.error;await refreshPatientData();if(category==='caregivers')await loadCaregivers();setNotice(p.archived?(category==='caregivers'?'Caregiver restored to pending approval. Approve the request before family access resumes.':'Record restored.'):(category==='caregivers'?'Caregiver archived and family access revoked.':'Record archived.'));}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <section aria-label="Archives"><h2>Archives</h2><nav className="support-nav" aria-label="Archive categories">{[['mothers','Mother'],['infants','Infant'],['caregivers','Caregiver']].map(([key,label])=><button key={key} className="family-primary" aria-pressed={category===key} onClick={()=>{setCategory(key);setQuery('');setError('');setNotice('');}}>{label}</button>)}</nav><p>{category==='caregivers'?'Archiving removes family access while keeping the caregiver record. Restored caregivers return to pending approval.':'Archive inactive records without deleting their clinical history.'}</p><div className="support-actions"><label>Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or record number"/></label><label>Show<select value={show} onChange={e=>setShow(e.target.value)}><option>Archived</option><option>Active</option></select></label></div>{(error||storageError)&&<p role="alert" className="support-message">{error||storageError}</p>}{notice&&<p role="status">{notice}</p>}{(loading||loadingRecords)&&<p role="status">Loading records…</p>}{rows.map(p=><article className="support-panel" key={p.id}><h3>{p.name}</h3><p>{category==='caregivers'?`${p.relationship} · ${p.contact_number||'No contact number'}`:p.recordCode}</p>{category==='caregivers'?<p>Requested patient: {p.requested_patient_name}<br/>Status: {p.archived?'Archived':p.status}</p>:<details><summary>Clinical history</summary>{reportRows({...data,mothers:category==='mothers'?[p]:[],infants:category==='infants'?[p]:[],appointments:data.appointments.filter(a=>a.patientId===p.id)},'0000-01-01','9999-12-31').map((r,i)=><p key={i}>{r.date} · {r.type}: {r.details}</p>)}</details>}<button disabled={busy||loading} onClick={()=>change(p)}>{p.archived?'Restore record':'Archive record'}</button></article>)}{!loading&&!loadingRecords&&!error&&!rows.length&&<p>No {show.toLowerCase()} {category} match your search.</p>}</section>;
}
