import { useEffect, useState } from 'react';
import { FamilyHeader } from './FamilyPortal';
import { PageStyles } from '../components/PageStyles';
import { supabase } from '../lib/supabase';
import { session } from '../care';
import './MotherProfile.css';

export default function CaregiverProfile() {
  const user = session(); const [profile, setProfile] = useState({ full_name: user.name || '', phone: '', avatar_url: '' }); const [phone, setPhone] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { supabase.from('profiles').select('full_name, phone, avatar_url').eq('id', user.id).single().then(({ data }) => { if (data) { setProfile(data); setPhone(data.phone || ''); } }); }, [user.id]);
  const save = async event => { event.preventDefault(); setBusy(true); const { error } = await supabase.rpc('update_my_caregiver_contact', { new_phone: phone }); setBusy(false); setNotice(error ? error.message : 'Contact number updated.'); };
  const upload = async event => { const file = event.target.files?.[0]; if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 2 * 1024 * 1024) return setNotice('Choose a PNG, JPEG, or WebP image up to 2 MB.'); setBusy(true); const ext = file.name.split('.').pop().toLowerCase(); const path = `${user.id}/avatar.${ext}`; const { error: uploadError } = await supabase.storage.from('avatars').upload(path, file, { upsert: true }); if (uploadError) { setBusy(false); return setNotice(uploadError.message); } const { data } = supabase.storage.from('avatars').getPublicUrl(path); const avatarUrl = `${data.publicUrl}?v=${Date.now()}`; const { error } = await supabase.rpc('update_my_caregiver_avatar', { new_avatar_url: avatarUrl }); setBusy(false); if (error) return setNotice(error.message); setProfile(current => ({ ...current, avatar_url: avatarUrl })); window.dispatchEvent(new CustomEvent('medimama-avatar-updated', { detail: avatarUrl })); setNotice('Profile photo updated.'); };
  const initials = profile.full_name.split(' ').map(part => part[0]).join('').slice(0, 2) || 'C';
  return <><PageStyles page="user" /><FamilyHeader /><main className="family-page mother-profile-page"><header><div><p>MediMama care</p><h1>Caregiver profile</h1><span>Update your contact details and profile photo.</span></div></header>{notice && <p className="mother-profile-notice">{notice}</p>}<section className="mother-profile-card"><div className="mother-avatar-wrap">{profile.avatar_url ? <img src={profile.avatar_url} alt="Profile" /> : <span>{initials}</span>}<label className="mother-avatar-edit"><i className="fa-solid fa-camera" /><input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} disabled={busy} /></label></div><div><h2>{profile.full_name}</h2><p>Caregiver account</p><small>PNG, JPEG, or WebP · maximum 2 MB</small></div></section><section className="mother-contact-card"><h2>Contact number</h2><p>Keep this number current so the health center can contact you about linked family care.</p><form onSubmit={save}><label>Philippine mobile number<div><span>+63</span><input value={phone} onChange={e => setPhone(e.target.value.replace(/\D/g, '').slice(0, 10))} placeholder="9XXXXXXXXX" required /></div></label><button className="family-primary" disabled={busy}>{busy ? 'Saving…' : 'Save changes'}</button></form></section></main></>;
}
