import { useEffect, useState } from 'react';
import { AdminShell } from '../components/AdminShell';
import { supabase } from '../lib/supabase';

function DetailsModal({ request, mothers, assignment, close, onSave, onDelete }) {
  const [busy, setBusy] = useState(false);
  const simplify = value => String(value || '').toLowerCase().replace(/[^a-z0-9]/g, '');
  const requestedName = simplify(request.requested_patient_name);
  const inferredMother = mothers.find(mother => {
    const name = simplify(mother.full_name);
    return requestedName && name && (requestedName.includes(name) || name.includes(requestedName));
  });
  const linkedMother = mothers.find(mother => mother.id === assignment?.mother_id) || inferredMother;
  const submit = async e => { e.preventDefault(); setBusy(true); await onSave(request, Object.fromEntries(new FormData(e.currentTarget))); setBusy(false); };
  const remove = async () => { if (!window.confirm(`Delete ${request.full_name}'s caregiver registration? This removes family access.`)) return; setBusy(true); await onDelete(request); setBusy(false); };
  return <div className="admin-modal" role="dialog" aria-modal="true"><section><button className="close" type="button" onClick={close} aria-label="Close">×</button><h2>Caregiver details</h2><div className="admin-profile"><span>{request.full_name.split(' ').map(p => p[0]).join('').slice(0, 2)}</span><div><strong>{request.full_name}</strong><small>{request.status === 'approved' ? 'Approved caregiver' : `${request.status} request`}</small></div></div><form className="admin-form" onSubmit={submit}><label>Contact number<input name="contact_number" defaultValue={request.contact_number || ''} inputMode="numeric" pattern="9[0-9]{9}" maxLength="10" required /></label><label>Relationship<input name="relationship" defaultValue={request.relationship || ''} required /></label><label className="full">Requested mother or patient<input name="requested_patient_name" value={linkedMother?.full_name || request.requested_patient_name || ''} readOnly /></label>{request.status === 'approved' ? <label className="full">Linked mother record<input value={linkedMother?.full_name || 'No linked mother record'} readOnly /><input type="hidden" name="mother_id" value={linkedMother?.id || ''} /></label> : <label className="full">Linked mother record<select name="mother_id" defaultValue={linkedMother?.id || ''}><option value="">Choose mother record</option>{mothers.map(m => <option key={m.id} value={m.id}>{m.full_name}</option>)}</select></label>}<p className="caregiver-detail-note">The mother name entered during registration is selected automatically. Saving updates the contact number and caregiver link.</p><div className="admin-form-actions"><button type="button" className="danger-button" disabled={busy} onClick={remove}>Delete record</button><button type="button" className="secondary" disabled={busy} onClick={close}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? 'Saving...' : 'Save changes'}</button></div></form></section></div>;
}

export default function CaregiverRequests() {
  const [requests, setRequests] = useState([]), [mothers, setMothers] = useState([]), [assignments, setAssignments] = useState([]), [selected, setSelected] = useState(null), [notice, setNotice] = useState('');
  const load = async () => { const [r, m, a] = await Promise.all([supabase.from('caregiver_requests').select('*').order('created_at', { ascending: false }), supabase.from('mothers').select('id, full_name'), supabase.from('caregiver_assignments').select('id, caregiver_id, mother_id, relationship, status')]); setRequests(r.data || []); setMothers(m.data || []); setAssignments(a.data || []); };
  useEffect(() => { load(); }, []);
  const assignmentFor = request => assignments.find(a => a.caregiver_id === request.caregiver_id);
  const linkedMotherFor = request => {
    const simplify = value => String(value || '').toLowerCase().replace(/[^a-z0-9]/g, '');
    const requested = simplify(request.requested_patient_name);
    return mothers.find(mother => {
      const name = simplify(mother.full_name);
      return requested && name && (requested.includes(name) || name.includes(requested));
    });
  };
  const writeAssignment = async (request, motherId, relationship) => { const old = assignmentFor(request), values = { caregiver_id: request.caregiver_id, mother_id: motherId, relationship, consent_confirmed_at: new Date().toISOString(), status: 'approved' }; return old ? supabase.from('caregiver_assignments').update(values).eq('id', old.id) : supabase.from('caregiver_assignments').insert(values); };
  const decide = async (request, status) => { const motherId = linkedMotherFor(request)?.id; if (status === 'approved' && !motherId) return setNotice('The requested mother name did not match a mother record. Please verify the name first.'); const { data: auth } = await supabase.auth.getUser(); if (status === 'approved') { const { error } = await writeAssignment(request, motherId, request.relationship); if (error) return setNotice(error.message); } const { error } = await supabase.from('caregiver_requests').update({ status, reviewed_by: auth.user.id, reviewed_at: new Date().toISOString() }).eq('id', request.id); if (error) return setNotice(error.message); setNotice(`Request ${status}.`); load(); };
  const saveDetails = async (request, values) => { const phone = values.contact_number.replace(/\D/g, ''); if (!/^9\d{9}$/.test(phone)) return setNotice('Enter a valid 10-digit Philippine mobile number.'); if (request.status === 'approved' && !values.mother_id) return setNotice('Choose the linked mother record before saving.'); const { error: profileError } = await supabase.from('profiles').update({ phone }).eq('id', request.caregiver_id); if (profileError) return setNotice(profileError.message); const { error } = await supabase.from('caregiver_requests').update({ contact_number: phone, relationship: values.relationship, requested_patient_name: values.requested_patient_name }).eq('id', request.id); if (error) return setNotice(error.message); if (request.status === 'approved') { const { error: assignmentError } = await writeAssignment(request, values.mother_id, values.relationship); if (assignmentError) return setNotice(assignmentError.message); } setSelected(null); setNotice('Caregiver record saved.'); load(); };
  const deleteRecord = async request => { const { error: assignmentError } = await supabase.from('caregiver_assignments').delete().eq('caregiver_id', request.caregiver_id); if (assignmentError) return setNotice(assignmentError.message); const { error } = await supabase.from('caregiver_requests').delete().eq('id', request.id); if (error) return setNotice(error.message); setSelected(null); setNotice('Caregiver record deleted and family access removed.'); load(); };
  const pending = requests.filter(r => r.status === 'pending').length;
  return <AdminShell page="mothers"><main className="main-content directory-page caregiver-requests-page"><header className="page-header"><div><p className="eyebrow">Caregiver management</p><h1>Caregiver Requests</h1><p>Review requests and confirm mother consent before granting access.</p></div></header>{notice && <p className="admin-toast">{notice}</p>}<section className="summary-grid caregiver-summary"><article><i className="fa-solid fa-clock" /><span><b>{pending}</b><small>Pending requests</small></span></article><article><i className="fa-solid fa-user-check" /><span><b>{requests.filter(r => r.status === 'approved').length}</b><small>Approved caregivers</small></span></article><article><i className="fa-solid fa-users" /><span><b>{mothers.length}</b><small>Available mother records</small></span></article></section><section className="directory-panel caregiver-table-panel"><div className="caregiver-table-head"><div><h2>Registration queue</h2><p>Caregiver requests are linked to the mother name provided during sign-up.</p></div><span>{requests.length} total requests</span></div><div className="table-wrap"><table><thead><tr><th>Caregiver</th><th>Relationship</th><th>Requested patient</th><th>Status</th><th>Review action</th></tr></thead><tbody>{requests.length ? requests.map(r => <tr key={r.id}><td><div className="caregiver-person"><span>{r.full_name.split(' ').map(x => x[0]).join('').slice(0, 2)}</span><div><strong>{r.full_name}</strong><small>{r.contact_number || 'No contact number'}</small></div></div></td><td>{r.relationship}</td><td>{r.requested_patient_name}</td><td><span className={`caregiver-status ${r.status}`}>{r.status}</span></td><td><div className="caregiver-row-actions">{r.status === 'pending' ? <div className="caregiver-actions"><div><button className="view-button" onClick={() => decide(r, 'approved')}><i className="fa-solid fa-check" /> Approve</button><button className="caregiver-decline" onClick={() => decide(r, 'declined')}><i className="fa-solid fa-xmark" /> Decline</button></div></div> : r.status === 'approved' ? <><button className="view-button" onClick={() => setSelected(r)}>View details</button><span className="caregiver-reviewed"><i className="fa-solid fa-circle-check" /> Reviewed</span></> : <span className="caregiver-reviewed">Reviewed</span>}</div></td></tr>) : <tr><td className="admin-empty" colSpan="5">No caregiver registrations yet.</td></tr>}</tbody></table></div></section>{selected && <DetailsModal request={selected} mothers={mothers} assignment={assignmentFor(selected)} close={() => setSelected(null)} onSave={saveDetails} onDelete={deleteRecord} />}</main></AdminShell>;
}
