import { useState } from 'react';
import { Link, NavLink } from 'react-router-dom';
import { PageStyles } from '../components/PageStyles';

const Icon = ({ name }) => <i className={`fa-solid fa-${name}`} />;
const navClass = ({ isActive }) => `nav-link${isActive ? ' active' : ''}`;
function Header() { return <header className="app-header"><Link className="brand" to="/user"><img src="/medimama/medimamalogo.png" alt="MediMama" /></Link><nav className="main-nav"><NavLink className={navClass} to="/user" end><Icon name="house" /><span>Home</span></NavLink><NavLink className={navClass} to="/user/appointments"><Icon name="calendar-days" /><span>Appointments</span></NavLink><NavLink className={navClass} to="/user/records"><Icon name="clipboard" /><span>Records</span></NavLink><NavLink className={navClass} to="/user/infants"><Icon name="baby" /><span>My Infants</span></NavLink><NavLink className={navClass} to="/caregiver"><Icon name="hand-holding-heart" /><span>Caregiver</span></NavLink></nav><div className="header-actions"><div className="user-pill"><span className="avatar">SS</span><span><strong>Shaina Santos</strong><small>Mother</small></span></div></div></header>; }
const appointments = [{ type: 'Postnatal Checkup', date: 'August 20, 2026', time: '8:30 AM', status: 'Confirmed' }, { type: 'Infant Growth Review', date: 'September 4, 2026', time: '10:00 AM', status: 'Upcoming' }, { type: 'Postnatal Consultation', date: 'September 15, 2026', time: '1:30 PM', status: 'Rescheduled' }];
function AppointmentPage() { const [filter, setFilter] = useState('All'); const [book, setBook] = useState(false); const rows = appointments.filter((item) => filter === 'All' || item.status === filter); return <Portal title="Upcoming visits" label="Appointments" description="Review your schedule and book an appointment with your barangay health center." action={() => setBook(true)} actionText="Book appointment"><div className="portal-pills">{['All','Confirmed','Upcoming','Rescheduled'].map((item) => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item}</button>)}</div><section className="portal-list">{rows.map((item) => <article key={item.type} className="portal-row"><div><strong>{item.type}</strong><small>{item.date} · {item.time}</small></div><span className={`family-status ${item.status.toLowerCase()}`}>{item.status}</span><button onClick={() => setBook(true)}>View details</button></article>)}</section>{book && <PortalModal title="Book an appointment" close={() => setBook(false)}><label>Service<select><option>Postnatal Checkup</option><option>Infant Growth Review</option><option>Immunization</option></select></label><label>Preferred date<input type="date" required /></label><button>Submit request</button></PortalModal>}</Portal>; }
const records = [{ type: 'Maternal History', detail: 'Blood pressure stable, hemoglobin 12.5 g/dL.', date: 'Aug 10, 2026', status: 'Completed' }, { type: 'Lab results', detail: 'Complete blood count and iron level.', date: 'Aug 05, 2026', status: 'Reviewed' }, { type: 'Vaccination', detail: 'Pentavalent 1 schedule reminder.', date: 'Aug 28, 2026', status: 'Due' }];
function RecordsPage() { const [query, setQuery] = useState(''); const shown = records.filter((item) => `${item.type} ${item.detail}`.toLowerCase().includes(query.toLowerCase())); return <Portal title="Patient and baby records" label="Health Records" description="Access recent maternal and infant health information in one place."><label className="portal-search"><Icon name="magnifying-glass" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search health records" /></label><section className="portal-list">{shown.map((item) => <article key={item.type} className="portal-row"><div><strong>{item.type}</strong><small>{item.detail} · {item.date}</small></div><span className="family-status completed">{item.status}</span><button>View record</button></article>)}</section></Portal>; }
function InfantsPage() { const [register, setRegister] = useState(false); return <Portal title="Baby health, all in one place." label="My Infants" description="Review verified growth and immunization records." action={() => setRegister(true)} actionText="Register an infant"><section className="infant-summary"><article><span>👶</span><div><strong>Baby Patrick Ibanez</strong><small>2 months old · Male</small><p>Weight: <b>5.2 kg</b> · Length: <b>58 cm</b></p></div></article><article><h2>Immunization checklist</h2><p>BCG and Hepatitis B complete</p><p className="due"><Icon name="syringe" /> Pentavalent 1 due August 28</p></article></section>{register && <PortalModal title="Register an infant" close={() => setRegister(false)}><InfantRegistrationForm /></PortalModal>}</Portal>; }
function InfantRegistrationForm() { return <><p className="registration-note">The health worker will review this information before activating the infant record.</p><fieldset><legend>Infant identity</legend><label>First name<input name="firstName" required autoComplete="given-name" /></label><label>Middle name<input name="middleName" autoComplete="additional-name" /></label><label>Surname<input name="surname" required autoComplete="family-name" /></label><label>Suffix<input name="suffix" placeholder="Jr., II (if applicable)" /></label><label>Date of birth<input name="birthDate" type="date" required /></label><label>Age<input name="ageMonths" type="number" min="0" max="60" required placeholder="Months" /></label><label>Sex<select name="sex" required><option value="">Select sex</option><option>Female</option><option>Male</option></select></label><label>Blood type<select name="bloodType"><option value="">Not yet known</option><option>A+</option><option>A-</option><option>B+</option><option>B-</option><option>AB+</option><option>AB-</option><option>O+</option><option>O-</option></select></label></fieldset><fieldset><legend>Birth and current measurements</legend><label>Place of birth<input name="placeOfBirth" required placeholder="Hospital, clinic, or city" /></label><label>Birth weight (kg)<input name="birthWeight" type="number" min="0" max="10" step="0.01" required /></label><label>Birth length (cm)<input name="birthLength" type="number" min="0" max="100" step="0.1" required /></label><label>Current weight (kg)<input name="currentWeight" type="number" min="0" max="40" step="0.01" required /></label><label>Current height / length (cm)<input name="currentHeight" type="number" min="0" max="150" step="0.1" required /></label></fieldset><fieldset><legend>Parent and medical information</legend><label>Mother / guardian name<input name="guardianName" required /></label><label>Guardian contact number<input name="guardianContact" type="tel" required placeholder="09XX XXX XXXX" /></label><label className="form-full">Known allergies<textarea name="allergies" placeholder="Write None if there are no known allergies" /></label><label className="form-full">Medical conditions or birth concerns<textarea name="medicalNotes" placeholder="Prematurity, complications, current medicine, or other notes" /></label></fieldset><button>Submit for approval</button></>; }
function CaregiverPage() { const [done, setDone] = useState([false, false, false]); const tasks = ['Give vitamin drops after breakfast', 'Track feeding at 12:00 PM', 'Prepare immunization card']; return <Portal title="Caregiver workspace" label="Care plan" description="Keep daily care tasks coordinated for Baby Patrick."><section className="portal-list">{tasks.map((task, index) => <label className="task-row" key={task}><input type="checkbox" checked={done[index]} onChange={() => setDone(done.map((value, i) => i === index ? !value : value))} /><span>{task}</span><b>{done[index] ? 'Done' : 'To do'}</b></label>)}</section><section className="portal-callout"><Icon name="calendar-days" /><div><strong>Next appointment</strong><p>Infant Immunization · September 15, 2026 at 9:00 AM</p></div></section></Portal>; }
function Portal({ title, label, description, action, actionText, children }) { return <><PageStyles page="user" /><Header /><main className="family-page"><header><div><p>{label}</p><h1>{title}</h1><span>{description}</span></div>{action && <button className="family-primary" onClick={action}><Icon name="plus" /> {actionText}</button>}</header>{children}</main></>; }
function PortalModal({ title, close, children }) { return <div className="family-modal" onMouseDown={(event) => event.target === event.currentTarget && close()}><form onSubmit={(event) => { event.preventDefault(); close(); }}><button type="button" className="family-close" onClick={close}>×</button><h2>{title}</h2><div>{children}</div></form></div>; }
export default function FamilyPortal({ page }) { return page === 'appointments' ? <AppointmentPage /> : page === 'records' ? <RecordsPage /> : page === 'infants' ? <InfantsPage /> : <CaregiverPage />; }
