import { spawn } from 'node:child_process';
import { mkdtemp, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import assert from 'node:assert/strict';
import { addDays, today } from '../src/care.js';

const pause = ms => new Promise(r => setTimeout(r, ms));
const profile = await mkdtemp(join(tmpdir(), 'medimama-ui-'));
const server = spawn(process.execPath, ['node_modules/vite/bin/vite.js', '--host', '127.0.0.1', '--port', '4179', '--strictPort'], { stdio: 'ignore', windowsHide: true });
const chrome = spawn('C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', ['--headless=new', '--disable-gpu', '--no-first-run', '--no-default-browser-check', '--remote-debugging-port=9231', `--user-data-dir=${profile}`, 'about:blank'], { stdio: 'ignore', windowsHide: true });
let ws;
const faults = [];
try {
  let target;
  for (let i = 0; i < 100; i++) {
    try { await fetch('http://127.0.0.1:4179'); target = await (await fetch('http://127.0.0.1:9231/json/new?about:blank', { method: 'PUT' })).json(); break; } catch { await pause(100); }
  }
  assert.ok(target, 'Headless browser and Vite started');
  ws = new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((r, reject) => { ws.onopen = r; ws.onerror = reject; });
  let seq = 0;
  const pending = new Map();
  ws.onmessage = event => {
    const message = JSON.parse(event.data);
    if (message.method === 'Runtime.exceptionThrown') faults.push(message.params.exceptionDetails.text + ': ' + message.params.exceptionDetails.exception?.description);
    if (message.id && pending.has(message.id)) { pending.get(message.id)(message); pending.delete(message.id); }
  };
  const send = (method, params = {}) => new Promise((resolve, reject) => { const id = ++seq; pending.set(id, msg => msg.error ? reject(Error(msg.error.message)) : resolve(msg.result)); ws.send(JSON.stringify({ id, method, params })); });
  const evaluate = async expression => { const response = await send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (response.exceptionDetails) throw Error(response.exceptionDetails.exception?.description || response.exceptionDetails.text); return response.result.value; };
  const waitFor = async expression => { for (let i = 0; i < 100; i++) { if (await evaluate(expression)) return; await pause(100); } throw Error(`Timed out: ${expression}`); };
  const visit = async path => { await send('Page.navigate', { url: 'http://127.0.0.1:4179' + path }); await waitFor('Boolean(document.querySelector(".care-workspace"))'); };
  const click = async text => { await evaluate(`(() => { const b = [...document.querySelectorAll('button')].find(b => b.textContent.trim() === ${JSON.stringify(text)}); if (!b) throw Error('Button missing: ' + ${JSON.stringify(text)}); b.click(); })()`); await pause(80); };
  const fill = async (name, value) => { await evaluate(`(() => { const el = document.querySelector('[role="dialog"] [name="${name}"]'); if (!el) throw Error('Field missing: ${name}'); const proto = el.tagName === 'SELECT' ? HTMLSelectElement.prototype : el.tagName === 'TEXTAREA' ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype; Object.getOwnPropertyDescriptor(proto, 'value').set.call(el, ${JSON.stringify(value)}); el.dispatchEvent(new Event('input', {bubbles:true})); el.dispatchEvent(new Event('change', {bubbles:true})); })()`); await pause(40); };
  const submit = async () => { await evaluate('document.querySelector("[role=dialog] form").requestSubmit()'); await pause(150); };
  const saved = async () => JSON.parse(await evaluate('localStorage.getItem("medimama-react-data")'));
  await send('Runtime.enable');
  await send('Page.enable');
  await send('Emulation.setDeviceMetricsOverride', { width: 1365, height: 900, deviceScaleFactor: 1, mobile: false });
  await send('Page.navigate', { url: 'http://127.0.0.1:4179/login' });
  await waitFor('Boolean(document.querySelector(".mm-login-page"))');
  const mother = { id: 'm-ui', accountId: 'u-ui', name: 'Test Mother', status: 'Pregnant', records: [], infantIds: [] };
  const account = { id: 'u-ui', email: 'mother@example.test', name: 'Test Mother', role: 'mother', status: 'approved' };
  const caregiver = { id: 'c-ui', email: 'caregiver@example.test', name: 'Test Caregiver', role: 'caregiver', status: 'approved' };
  const fixture = { mothers: [mother], infants: [], appointments: [], caregivers: [{ id: 'link-ui', accountId: 'c-ui', motherId: 'm-ui', status: 'Approved' }] };
  await evaluate(`localStorage.setItem('medimama-react-data', ${JSON.stringify(JSON.stringify(fixture))}); localStorage.setItem('medimama-accounts', ${JSON.stringify(JSON.stringify([account, caregiver]))}); localStorage.setItem('medimama-current-session', ${JSON.stringify(JSON.stringify(account))});`);
  await visit('/user/infants');
  await click('Register infant');
  for (const [name, value] of Object.entries({ firstName: 'Test', surname: 'Baby', birthDate: '2026-08-01', placeOfBirth: 'Test Hospital', address: 'Test address', guardianContact: '09171234567', birthWeight: '3.1', birthLength: '49', weight: '4.2', length: '54', muac: '12' })) await fill(name, value);
  await submit();
  let state = await saved();
  assert.equal(state.infants.length, 1, 'Mother infant registration persisted');
  assert.equal(state.infants[0].status, 'Pending approval');
  assert.equal(state.infants[0].growth[0].muac, '12');
  await evaluate(`localStorage.setItem('medimama-current-session', ${JSON.stringify(JSON.stringify({ role: 'admin', name: 'Test Admin', email: 'admin@medimama.test' }))})`);
  await visit('/');
  await click('Approve registration');
  assert.equal((await saved()).infants[0].status, 'Active');
  await click('Update intake / delivery');
  for (const [name, value] of Object.entries({ gestationWeeks: '12', gestationDate: today(), hospital: 'Test Hospital', hospitalSummary: 'Hospital intake received', priorVisits: '3' })) await fill(name, value);
  await submit();
  assert.equal((await saved()).mothers[0].priorVisits, '3');
  assert.ok(await evaluate('document.body.innerText.includes("5 of 8")'));
  await click('Record dose');
  await fill('provider', 'Test Nurse');
  await evaluate('document.querySelector("[role=dialog] input[type=checkbox]").click()');
  await submit();
  assert.equal((await saved()).infants[0].vaccines[0].vaccine, 'BCG');
  await click('Record screening');
  await fill('result', 'Screening completed; result reviewed');
  await submit();
  assert.equal((await saved()).infants[0].screenings.length, 1);
  await click('Add measurements');
  for (const [name, value] of Object.entries({ date: addDays(today(), -1), weight: '4.1', length: '53.8', muac: '11.9' })) await fill(name, value);
  await submit();
  assert.equal((await saved()).infants[0].growth.length, 2, 'Growth history preserves registration measurements');
  await click('Record clinic visit');
  await fill('date', '2026-08-10'); await fill('details', 'Newborn review completed'); await submit();
  assert.ok(await evaluate('document.body.innerText.includes("Visit within first six weeks recorded")'));
  await evaluate(`localStorage.setItem('medimama-current-session', ${JSON.stringify(JSON.stringify(account))})`);
  await visit('/user/appointments');
  await click('Book appointment');
  let date = addDays(today(), 7);
  while (new Date(date + 'T00:00:00Z').getUTCDay() !== 3) date = addDays(date, 1);
  await fill('date', date); await fill('time', '10:00'); await submit();
  assert.equal((await saved()).appointments.length, 1);
  await click('Reschedule');
  await fill('date', addDays(date, 7)); await fill('reason', 'Feeling unwell'); await submit();
  state = await saved();
  assert.equal(state.appointments[0].history.length, 1);
  assert.equal(state.appointments[0].reason, 'Feeling unwell');
  await visit('/user/appointments');
  assert.ok(await evaluate('document.body.innerText.includes("Feeling unwell")'), 'Reschedule survives reload');
  await evaluate(`localStorage.setItem('medimama-current-session', ${JSON.stringify(JSON.stringify({ role: 'admin', name: 'Test Admin', email: 'admin@medimama.test' }))})`);
  await visit('/');
  assert.ok(await evaluate('document.body.innerText.includes("Feeling unwell")'), 'Admin sees the reschedule reason');
  await click('Update intake / delivery');
  await fill('deliveryDate', today()); await submit();
  assert.equal((await saved()).mothers[0].status, 'Postnatal', 'Delivery switches the maternal stage');
  await click('Record checkup'); await fill('details', 'Postnatal review completed'); await submit();
  assert.equal((await saved()).mothers[0].records.at(-1).type, 'Postnatal check-up');
  await mkdir('artifacts', { recursive: true });
  const adminShot = await send('Page.captureScreenshot', { format: 'png' });
  await writeFile('artifacts/admin-desktop.png', Buffer.from(adminShot.data, 'base64'));
  await evaluate(`localStorage.setItem('medimama-current-session', ${JSON.stringify(JSON.stringify(caregiver))})`);
  await visit('/caregiver');
  assert.equal(await evaluate('Boolean(document.querySelector(".main-nav"))'), false, 'Caregiver header has no duplicate navbar');
  assert.equal(await evaluate('Boolean(document.querySelector(".family-overview"))'), true);
  await click('Appointments');
  assert.ok(await evaluate('document.body.innerText.includes("Feeling unwell")'));
  await click('Records');
  assert.ok(await evaluate('document.body.innerText.includes("Test Baby") && document.body.innerText.includes("Maternal records")'));
  await visit('/caregiver?tab=records');
  assert.equal(await evaluate('document.querySelector(".caregiver-tabs button[aria-pressed=true]").textContent'), 'Records', 'Tab survives reload');
  assert.equal(await evaluate('[...document.querySelectorAll("button")].some(b => ["Record dose", "Register infant", "Book appointment"].includes(b.textContent.trim()))'), false, 'Caregiver has read-only access');
  await mkdir('artifacts', { recursive: true });
  await click('Overview');
  const shot = await send('Page.captureScreenshot', { format: 'png' });
  await writeFile('artifacts/caregiver-desktop.png', Buffer.from(shot.data, 'base64'));
  await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  await pause(200);
  assert.equal(await evaluate('document.documentElement.scrollWidth <= window.innerWidth'), true, 'No horizontal page overflow on mobile');
  const mobileShot = await send('Page.captureScreenshot', { format: 'png' });
  await writeFile('artifacts/caregiver-mobile.png', Buffer.from(mobileShot.data, 'base64'));
  await evaluate(`localStorage.setItem('medimama-current-session', ${JSON.stringify(JSON.stringify(account))})`);
  await visit('/user');
  assert.equal(await evaluate('Boolean(document.querySelector(".family-overview"))'), true, 'Mother home shows summary');
  assert.equal(await evaluate('Boolean(document.querySelector(".care-table-wrap"))'), false, 'Home has no full record tables');
  await visit('/user/records');
  assert.equal(await evaluate('document.body.innerText.includes("Immunization checklist")'), false, 'Maternal records exclude infant details');
  await visit('/user/infants');
  assert.ok(await evaluate('document.body.innerText.includes("Immunization checklist")'));
  assert.equal(await evaluate('document.body.innerText.includes("Maternal records")'), false, 'Infant page excludes maternal records');
  assert.deepEqual(faults, [], 'No runtime exceptions');
  console.log('PASS: registration, admin approval, maternal intake/delivery, growth history, newborn visit, vaccine/screening records, booking, rescheduling, reload persistence, caregiver access, and mobile layout.');
} finally {
  ws?.close();
  chrome.kill();
  server.kill();
}
